### ISSUE TITLE
Migration to API V3

### ISSUE THREAD

**Issue by kamilbednarz** [relrod/bing_translator-gem#42]
Hey guys,

I'm not sure if you saw the emails Microsoft was sending out to their customers, but they' re going to discontinue the service of Bing translator V2 on April 30, 2019.

I'm wondering if you plan on getting this reflected in the Gem and switch to V3? I'm happy to help!

Best,
Kamil

**Comment by abrisse** [comment]
Hello Kamil,

You can use https://github.com/PerfectMemory/translator-text that uses the
V3 API. It's a full rewrite gem.

Cheers,

Aymeric

**Comment by relrod** [comment]
@kamilbednarz If you'd like to send a PR for it, I'd happily merge it. Otherwise I can add it to my list and take a look at some point before then. Thank you for bringing it to my attention.

**Comment by bvogel** [comment]
@relrod Thank you for your work! Today I received another reminder that the API will expire soon. Any plans to migrate your code or should we look into alternatives?

**Comment by relrod** [comment]
@bvogel It's still on my list, I'll try to have something to report in the next few days.

**Comment by relrod** [comment]
For those tracking this issue: How important is the speech stuff to everyone? It looks like MS moved this into [a separate API](https://docs.microsoft.com/en-gb/azure/cognitive-services/speech-service/rest-apis), and it's tempting to just drop it from this gem rather than having to implement two (arbitrary-ish, mostly-unrelated) APIs. But if people use it and need it, I can give it a try. 

Disadvantages of keeping it:

* Like I said above, it means we're supporting two mostly-unrelated MS APIs in this library which feels weird and would purely be for backwards compatibility for people.
* We have to keep using the `Bearer` auth token authentication instead of just passing in `Ocp-Apim-Subscription-Key` each request. This isn't too big of a deal but means keeping some annoying logic (so we know when to renew the token, etc.)
* More to support if something goes wrong. I rarely write Ruby anymore. I'm porting this to V3 because, well, someone has to do it since people use this library, but unless someone actively reports issues, I don't spend much time working with this library -- so keeping things I need to support to a minimum is quite nice.

Advantages:

* Backwards compatibility
* Prevents someone from having to use/find a lib if they end up needing speech services.

Discuss, please!

**Comment by bvogel** [comment]
Hi @relrod, for us the speech stuff is completely irrelevant, we really focus on translation and as the gem-name suggests so does the gem. We#d be completely fine with just text translation and any work you put into this on your free time is highly appreciated.

**Comment by kamilbednarz** [comment]
I'm ok with that, we don't use speech either. 

For anyone tracking this: I'm making progress with that, so far I got the authentication, translation and language detection working with v3.0:
https://github.com/kamilbednarz/bing_translator-gem/commits/feature/api-v3
At this point I just make it work, without worrying too much about the code quality. I'll take care of that when I complete the functional changes.

I want to complete all the migration within next 1-2 weeks. 
I do not migrate Speech. 

I noticed one problematic change in the API: Translations for texts longer than 5k characters are not allowed (reference: https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-translate?tabs=curl).

**Comment by relrod** [comment]
@kamilbednarz Oh cool. I had already started on this but hadn't pushed anything yet. I wasn't aware you were working on it. I had switched to using `rest-client`, but it was a fairly arbitrary choice. As mentioned above, I don't often write ruby nowadays, so I'm not sure what all the "in" tooling is right now.

It looks like you've made more progress than I have. So I can hold off my work for now, or if you'd like, I can give you commit on this repo and you can just work here. Whatever makes it easiest for you; I sincerely appreciate your work on this.

**Comment by kamilbednarz** [comment]
@relrod I'm so sorry! I should have told you I started this to not double the work. 

It would be awesome, if you could grant me write permissions, I can help you with maintaining this (I've been using it for a client anyway). 

BTW: I didn't want to use any of the rest clients to not complicate the dependencies on the apps that use this gem.

**Comment by relrod** [comment]
> if you could grant me write permissions, I can help you with maintaining this

Done and happy to have the help! Thank you for your work!

**Comment by relrod** [comment]
@kamilbednarz Hey, just checking in and seeing how this is coming along. We're coming up on two months until MS's cutover, so hopefully we can have something for people to test soonish? Let me know if I can help at all :)

**Comment by kamilbednarz** [comment]
Oh sorry, I was hammered with other work. I should get it done this week.

**Comment by kamilbednarz** [comment]
Hey there, 

I released a beta version of the migrated library. Simply bump up the gem version to `6.0.0.beta.2` if you want to try it out.

I'm going to test it with my project, but I'd appreciate any feedback/help with testing.

**Comment by kamilbednarz** [comment]
Hey there,

I just released `6.0.0` that is migrated to API V3.

I found one problem with `detect` function: Microsoft silently dropped support for some of the languages, more details here:
https://github.com/MicrosoftDocs/azure-docs/issues/29223

Also - `detect` codes for some of the languages have changed:
```
     V3,     V2
zh-Hans, zh-CHS
zh-Hant, zh-CHT
 fil-PH,    fil
   Gujr,     gu
   Knda,     kn
   Mlym,     ml
  mt-MT,     mt
     nb,     no
   Guru,     pa
```
So I suggest adjusting your configs if you rely on that.

**Comment by kamilbednarz** [comment]
We've been successfully running `6.0.0` in production a couple of days without a trouble.
(we're detecting languages 50k times/day).

Reminder: today is the last day of V2: 
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/migrate-to-v3

**Comment by relrod** [comment]
@kamilbednarz Sorry, never responded to this. Thanks so much again for your work on this!
